services:

  bench-profiles-service:
    image: bhargavivennam/bench-profiles-service
    ports:
      - "8081:8081"
    networks:
      - consulting_firm_network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dev-aurora-postgresql-auroradbinstance-4xndvv5lf7k1.cmstfl08uvou.us-east-1.rds.amazonaws.com:3306/$POSTGRES_DB
      SPRING_DATASOURCE_USERNAME: $POSTGRES_USER
      SPRING_DATASOURCE_PASSWORD: $POSTGRES_PASSWORD

  common-excel-service:
    image: bhargavivennam/common-excel-service
    ports:
      - "8083:8083"
    networks:
      - consulting_firm_network

volumes:
  postgres_data:
    driver: local

networks:
  consulting_firm_network:
    driver: bridge
